enhance build script to validate chosen kernel version and list available versions

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,15 +4,46 @@ set -e
 ARCH=loongarch
 CROSS_COMPILE=loongarch64-unknown-linux-gnu-
 
-# set to `6.13.7`/ `git` in the ./chosen file
+print_available_versions() {
+    echo "Available versions to set in the ./chosen file:"
+    # dump all the dirname with linux-*
+    cnt=0
+    for dir in $(ls -d linux-*); do
+        if [ -d "$dir" ]; then
+            # get the suffix of the directory
+            suffix=${dir#linux-}
+            cnt=$((cnt + 1))
+            echo "$cnt) $suffix"
+        fi
+    done
+}
+
+# if chosen file is not present, print error and exit
+if [ ! -f chosen ]; then
+    echo "Error: chosen file not found. Please set the kernel version suffix in the chosen file."
+    print_available_versions
+    exit 1
+fi
+
 CHOSEN=$(cat chosen)
+
+check_chosen() {
+    if [ ! -d "linux-$1" ]; then
+        echo "Error: linux-$1 directory not found. Please set the kernel version suffix in the chosen file."
+        print_available_versions
+        exit 1
+    fi
+}
+
+# check if linux-$CHOSEN directory exists
+check_chosen $CHOSEN
 
 # first we recursively clone all submodules
 
 init_submodules() {
     echo "Initializing submodules"
     git submodule update --init --recursive
-    echo "Chosen linux source: $CHOSEN"
+    echo "Chosen linux source: linux-$CHOSEN"
     echo "======================================================================="
     echo "Submodules:"
     git submodule status
